# Generated by Django 6.0.5 on 2026-05-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('active_stalls', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Admin Stats',
            },
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=100)),
                ('items', models.JSONField()),
                ('total', models.IntegerField()),
                ('mode', models.CharField(choices=[('dine_in', 'Dine-in'), ('takeaway', 'Takeaway')], max_length=20)),
                ('pickup_time', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('accepted', 'Accepted'), ('ready', 'Ready'), ('picked_up', 'Picked up')], max_length=20)),
                ('ready_for_pickup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.stall')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=50)),
                ('portions', models.JSONField(blank=True, null=True)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='api.stall')),
            ],
        ),
    ]
